# CV REFINEMENT

# CV parsing by pyresparser

In [1]:
from pdfminer.pdftypes import PDFObjectNotFound
from io import StringIO
import os
os.chdir('C:\\Users\\Abhishek_2\\Desktop\\cv2')
from pyresparser import ResumeParser
Name=[]
Email=[]
Mobile_number=[]
Skills=[]
College_name=[]
Degree=[]
Designation=[]
Experience=[]
Company_names=[]
No_of_pages=[]
Total_experience=[]
file=os.listdir('C:\\Users\\Abhishek_2\\Desktop\\cv2')

In [2]:
for filename in file:
    
    data = ResumeParser(filename).get_extracted_data()
    Name.append(data['name'])
    Email.append(data['email'])
    Mobile_number.append(data['mobile_number'])
    Skills.append(data['skills'])
    College_name.append(data['college_name'])
    Degree.append(data['degree'])
    Designation.append(data['designation'])
    Experience.append(data['experience'])
    Company_names.append(data['company_names'])
    
    Total_experience.append(data['total_experience'])
    
import pandas as pd
d = { 'Name': Name,
'Email':Email,
'Mobile_number':Mobile_number,
'Skills':Skills,
'College_name':College_name,
'Degree':Degree,
'Designation':Designation,
'Experience':Experience,
'Company_names':Company_names,

'Total_experience':Total_experience}

Resume_data=pd.DataFrame(data=d)
Resume_data

C:\Users\Abhishek_2\anaconda3\envs\python3\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.2). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

,Name,Email,Mobile_number,Skills,College_name,Degree,Designation,Experience,Company_names,Total_experience
0,abhishekgoel13197@gmail.com Abhishek,abhishekgoel13197@gmail.com,9650893638,"[Operations, Computer science, Cloud, C, Stand...",None,None,None,None,[Microsoft],0.00
1,Abhishek Goel,abhishekgoel13197@gmail.com,9650893638,"[Operations, Computer science, Cloud, C, Stand...",None,[Bachelor of Technology (Information Technolog...,None,[ Monitor performance of thermal cameras vir...,None,0.00
2,Brendan Herger,13herger@gmail.com,582-7457,"[Sas, Acquisition, Html5, Modeling, Supervisor...",None,None,[Front End Supervisor],"[Data Scientist, Data Innovation Lab @ Capital...",None,0.00
3,BHAUMIK S. SHAH,id:bhaumik24ss@gmail.com,8866300564,"[Sas, Business intelligence, Operations, Sql, ...",None,[PG DIPLOMA IN DATA SCIENCE],None,None,None,0.00
4,Regression models,None,014-2018,"[Brand, Operations, Ai, Sql, Engineering, Anal...",None,"[Civil Engineering \n\n, Bachelor of Technol...","[Business Analyst Intern, Machine Learning ...",None,None,0.00
5,Layla Martin,layla.d.martin@gmail.com,271-2492,"[Training, Matlab, Math, Mysql, Postgresql, R,...",None,"[Bachelor of Science in Mathematics, Cum Laude...",None,None,None,0.00
6,Madhav Institute of Technology and Science,nishkarshm.jain@outlook.com,8120907555,"[Opencv, Moviepy, Matplotlib, Retail, Sql, Eng...",None,[Bachelor of Engineering: Electronics],None,"[Accenture, Associate Software Engineer, • Wor...",None,1.42
7,MONICA MEYER,monica.meyer@comcast.net,None,"[Policies, Operations, Json, Retail, Apis, Tra...",None,"[Bachelor of Arts in Mathematics, Master of Sc...",None,"[Bank of America, Sales and Service Specialist...",None,1.33
8,VENKATESWARA S,venkat0990@gmail.com|,977-0479,"[Sas, Testing, Certification, Autocad, Segment...",None,None,None,"[Predictive Solutions LLC (Remote), Data Scien...",None,0.00

convert to pdf,doc to text

In [3]:
import re
from io import StringIO
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
import docx2txt

# Read in PDF complicated text using Pdfminer
def pdf_text_reader(pdf_file_name, pages=None):
    if pages:
        pagenums = set(pages)
    else:
        pagenums = set()

    # 1) Initiate the Pdf text converter and interpreter
    textOutput = StringIO()
    manager = PDFResourceManager()
    converter = TextConverter(manager, textOutput, laparams=LAParams())
    interpreter = PDFPageInterpreter(manager, converter)

    # 2) Extract text from file using the interpreter
    infile = open(pdf_file_name, 'rb')
    for page in PDFPage.get_pages(infile, pagenums):
        interpreter.process_page(page)        
    infile.close()
    
    # 3) Extract the paragraphs and close the connections
    paras = textOutput.getvalue()   
    converter.close()
    textOutput.close
    return paras



if __name__ == '__main__':
    file2=os.listdir('C:\\Users\\Abhishek_2\\Desktop\\cv2')
    ass = []
    for filename2 in file2:
            a = filename2.replace('.',',')
            if re.search(r'\b' + 'pdf' + r'\b', a):
                out = pdf_text_reader(filename2, pages=[0])   
                #asd = ([i for i in out.split('\n') if i])
                ass.append(out)
            else:
                docx = docx2txt.process(filename2)
                ass.append(docx)

In [4]:
Resume_data['cv_text']=ass

In [5]:
Resume_data

,Name,Email,Mobile_number,Skills,College_name,Degree,Designation,Experience,Company_names,Total_experience,cv_text
0,abhishekgoel13197@gmail.com Abhishek,abhishekgoel13197@gmail.com,9650893638,"[Operations, Computer science, Cloud, C, Stand...",None,None,None,None,[Microsoft],0.00,abhishekgoel13197@gmail.com\n\nAbhishek Goel\n...
1,Abhishek Goel,abhishekgoel13197@gmail.com,9650893638,"[Operations, Computer science, Cloud, C, Stand...",None,[Bachelor of Technology (Information Technolog...,None,[ Monitor performance of thermal cameras vir...,None,0.00,Abhishek Goel \n\nProfile: \n\n \n\n \n\n \n\n...
2,Brendan Herger,13herger@gmail.com,582-7457,"[Sas, Acquisition, Html5, Modeling, Supervisor...",None,None,[Front End Supervisor],"[Data Scientist, Data Innovation Lab @ Capital...",None,0.00,Brendan Herger\n\nHergertarian.com | 13herger@...
3,BHAUMIK S. SHAH,id:bhaumik24ss@gmail.com,8866300564,"[Sas, Business intelligence, Operations, Sql, ...",None,[PG DIPLOMA IN DATA SCIENCE],None,None,None,0.00,BHAUMIK S. SHAH\n\nPhone:- 8866300564 / 911389...
4,Regression models,None,014-2018,"[Brand, Operations, Ai, Sql, Engineering, Anal...",None,"[Civil Engineering \n\n, Bachelor of Technol...","[Business Analyst Intern, Machine Learning ...",None,None,0.00,\n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n ...
5,Layla Martin,layla.d.martin@gmail.com,271-2492,"[Training, Matlab, Math, Mysql, Postgresql, R,...",None,"[Bachelor of Science in Mathematics, Cum Laude...",None,None,None,0.00,Layla Martin\n\n2038 McAllister St\nSan Franci...
6,Madhav Institute of Technology and Science,nishkarshm.jain@outlook.com,8120907555,"[Opencv, Moviepy, Matplotlib, Retail, Sql, Eng...",None,[Bachelor of Engineering: Electronics],None,"[Accenture, Associate Software Engineer, • Wor...",None,1.42,NISHKARSH JAIN \n\nnishkarshm.jain@outlook.com...
7,MONICA MEYER,monica.meyer@comcast.net,None,"[Policies, Operations, Json, Retail, Apis, Tra...",None,"[Bachelor of Arts in Mathematics, Master of Sc...",None,"[Bank of America, Sales and Service Specialist...",None,1.33,MONICA MEYER\n\n(415) · 497 · 7282 (cid:5) mon...
8,VENKATESWARA S,venkat0990@gmail.com|,977-0479,"[Sas, Testing, Certification, Autocad, Segment...",None,None,None,"[Predictive Solutions LLC (Remote), Data Scien...",None,0.00,VENKY (VENKATESWARA S KRISHNAMOORTHY) \nvenkat...

In [6]:
Resume_data.to_csv('resume0.csv')

In [7]:
#import pandas as pd
#df = pd.read_csv(r"C:\Users\Abhishek_2\jupiter notebook\shineds0.csv")
#df = df.drop('Unnamed: 0', axis = 1)

for one to one matching

In [8]:
#import re
#import ast
#resume = []
#skills1 = ast.literal_eval(df['TechSkillMatch'][8]) #for converting string list to list
#skills1 = list(skills1.keys())
#tt0 = Resume_data['cv_text'][1]
#tt1 = tt0.replace('\n','')
#tt1 = tt1.lower()
#
#for i in range(len(skills1)):
#    asd = re.findall(r'\b' + skills1[i] + r'\b',tt1)
#    resume.append(asd)
#
##resume = pd.DataFrame(resume)
##resume
#
#Resume = []
#for i in range(len(resume)):
#    if(len(resume[i])==0):
#        Resume.append(0)
#    else:
#        Resume.append(len(resume[i]))
##Resume
#
#import ast
#skills1 = ast.literal_eval(df['TechSkillMatch'][8]) #for converting string dict to dict
#new = pd.DataFrame.from_dict([skills1])
#new = new.transpose()
#new.columns = ['job_desc']
##new
#
#new['Resume']= Resume
#new

for one to many

In [9]:
#import re
#import ast
#
#skills1 = ast.literal_eval(df['TechSkillMatch'][1]) #for converting string list to list
#skills1 = list(skills1.keys())
#resumemutli=[]
#for j in range(5):
#    tt0 = Resume_data['cv_text'][j]
#    tt1 = tt0.replace('\n','')
#    tt1 = tt1.lower()
#    resume = []
#    for i in range(len(skills1)):
#        asd = re.findall(r'\b' + skills1[i] + r'\b',tt1)
#        resume.append(asd)
#    
#
#    #resume = pd.DataFrame(resume)
#    resumemutli.append(resume)
##resumemutli
#
#Resumemutli1 = []
#for i in range(len(resumemutli)):
#    Resumemutli = []
#    for j in range(len(resumemutli[i])):
#        if(len(resumemutli[i][j])==0):
#            Resumemutli.append(0)
#        else:
#            Resumemutli.append(len(resumemutli[i][j]))
#    Resumemutli1.append(Resumemutli)
##Resumemutli1
#
#import ast
#skills1 = ast.literal_eval(df['TechSkillMatch'][1]) #for converting string dict to dict
#new = pd.DataFrame.from_dict([skills1])
#new = new.transpose()
#new.columns = ['job_desc']
##new
#
#for i in range(len(Resumemutli1)):
#    new['Resume',i]= Resumemutli1[i]
#new